#!/bin/bash

# Checks if a command is valid
function installed {
    command -v $1 >/dev/null 2>&1 || return 1
}

# Delete any files that were generated by the build
function clean {
    make clean
    phpize --clean
}

# Build
function build {
    phpize
    ./configure
    make && sudo make install || return 1
    clean
}

# Check that build tools are installed
if ! installed autoconf; then
    sudo apt-get update
    sudo apt-get install -y build-essential autoconf
fi

# Check that dev dependencies are installed for phpize
if ! installed phpize; then
    sudo add-apt-repository -y ppa:ondrej/php
    sudo apt-get update
    sudo apt-get install -y php7.0-dev
fi

if build; then
    echo "----------------------------------------------------------------------"
    echo "Success!"
    echo "Add 'extension=ds.so' to your .ini or use 'php -d extension=ds.so'"
    echo "----------------------------------------------------------------------"
    echo "$(php -i | grep php.ini)"
fi

